apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mqtt-access-logs
  namespace: default
spec:
  selector:
    matchLabels:
      app: mqtt-edge  # <--- ต้องตรงกับ Label ของ Pod MQTT
  accessLogging:
    - providers:
      - name: envoy