name: CI - Quality Control

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yamllint
        run: sudo apt-get install yamllint -y

      - name: Run yamllint
        # ไม่ต้อง echo สร้าง config แล้ว! มันจะอ่านจากไฟล์ .yamllint เอง
        run: |
          echo "🔍 Starting YAML Lint check..."
          yamllint .
          echo "✅ YAML files are valid!"
